version: '3.7'
services:
  service1:
    image: michaelacook1/service1:latest
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 3
  service2:
    image: michaelacook1/service2:latest
    build: ./service2
    ports:
    - target: 5001
      protocol: tcp
    deploy:
      replicas: 3
  service3:
    image: michaelacook1/service3:latest
    build: ./service3
    ports:
    - target: 5002
      protocol: tcp
    deploy:
      replicas: 3
  service4:
    image: michaelacook1/service4:latest
    build: ./service4
    ports:
    - target: 5003
      protocol: tcp
    deploy:
      replicas: 3
