version: '3.7'
services:
  service1:
    image: michaelacook1/service1:latest
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
              DATABASE_URI: mysql+pymysql://root:root@34.89.119.24/attempts:3306
    depends_on:
    -db
    deploy:
      replicas: 3
  service2:
    image: michaelacook1/service2:latest
    build: ./service2
    ports:
    - target: 5001
      protocol: tcp
    deploy:
      replicas: 3
  service3:
    image: michaelacook1/service3:latest
    build: ./service3
    ports:
    - target: 5002
      protocol: tcp
    deploy:
      replicas: 3
  service4:
    image: michaelacook1/service4:latest
    build: ./service4
    ports:
    - target: 5003
      protocol: tcp
    deploy:
      replicas: 3
  db:
    image: michaelacook1/db:latest
    build: ./db
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attempts_db
    volumes:
    - type: volume
      source: attempts
      target: /var/lib/mysql
volumes:
  attempts:
