
- name: "Init a new swarm with default parameters"
  shell: docker swarm init
- name: "Get swarn info"
  docker_swarm_info:
  register: swarm_info
- debug:
    msg: "Swarm Info: {{ swarm_info }}"
- name: "Get worker token"
  add_host:
    name: "token"
    value: "{{ swarm_info['swarm_facts']['JoinTokens']['Worker'] }}"
