- name: clone git 
  git:
    repo: https://github.com/MichaelaCook1/practicalproject
    dest: /home/practicalproject
    update: yes

- name: "Making the swarm"
  docker_swarm:
    state: present
- name: "Getting swarm info"
  docker_swarm_info:
  register: swarm_info

        
- name: "Getting a join token"
  add_host:
    name: "token"
    value: "{{ swarm_info['swarm_facts']['JoinTokens']['Worker'] }}"
