apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels:
    app: service1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service11
    spec:
      containers:
      - name: service1
        image: michaelacook1/serv1i:latest
        ports: 
         -name: index
         containerPort: 5000 
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: michaelacook1/serv2i:latest
          ports:
            - name: d20
              containerPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels:
    app: service3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
        - name: service3
          image: michaelacook1/serv3i:latest
          ports:
            - name: d12
              containerPort: 5002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
  labels:
    app: service4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
        - name: service4
          image: michaelacook1/serv4i:latest
          ports:
            - name: result
              containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: service1

---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  selector:
    app: service3
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service4
spec:
  selector:
    app: service4
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
---

