- name: 'updates and installations'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    
    
    state: latest
    update_cache: true

- name: 'adding GPG key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "making a repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          

- name: 'installing docker'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest


- name: "adding user to the docker group"
  user:
        name: "jenkins"
        group: docker
        state: present


- name: Install Python3
  apt:
    name: python3
    state: latest
    update_cache: true

- name: Install Pip3
  apt:
    name: python3-pip
    state: latest
    update_cache: true

- name: Install setuptools
  pip:
    name: setuptools
    executable: pip3
    state: latest

- name: Install Docker SDK
  pip:
    name: docker
    executable: pip3
